# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: GnomeWin.GnomeWin
PackageVersion: 1.0.0
MinimumOSVersion: 10.0.19041.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --install --quiet --startup
  SilentWithProgress: --install --quiet --startup
  Interactive: --install
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: GnomeWin
  Publisher: GnomeWin
  DisplayVersion: 1.0.0
  ProductCode: GnomeWin
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/traxcs/GNOME-WINDOWS/releases/download/v1.0.0/GnomeWin-Setup.exe
  InstallerSha256: 416B8DF6838408BD99658FE4FA5D860DF7F6BA39623DB15CB5F747B42696B767
ManifestType: installer
ManifestVersion: 1.6.0
